CREATE TABLE Countries(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Countrycode BIGINT NOT NULL UNIQUE,
Countryname VARCHAR(100) NOT NULL,
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Permission(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Permcode BIGINT NOT NULL UNIQUE,
Permname VARCHAR(100) NOT NULL,
Description VARCHAR(100) NOT NULL,
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Roles(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Rolecode BIGINT NOT NULL UNIQUE,
Rolename VARCHAR(100) NOT NULL,
Description VARCHAR(100) NOT NULL,
Issysgen BIT NOT NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Lnkrolepermission(
Rolecode BIGINT NOT NULL,
Permcode BIGINT NOT NULL,
)
CREATE TABLE Account(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Acccode BIGINT NOT NULL UNIQUE,
Tenantname VARCHAR(100) NOT NULL UNIQUE,
Tenantemail VARCHAR(100) NOT NULL UNIQUE,
Tenantdomain VARCHAR(100) NOT NULL UNIQUE,
Tenantconnid VARCHAR(100) NOT NULL,
Tenantconnkey VARCHAR(100) NOT NULL,
Tenantconndata VARCHAR(300) NOT NULL,
Authkey VARCHAR(100) NOT NULL,
Currency VARCHAR(100) NOT NULL,
Countrycode BIGINT NOT NULL,
Isactive BIT NOT NULL DEFAULT 1,
Isdeleted BIT NOT NULL DEFAULT 0,
Islive BIT NOT NULL DEFAULT 0,
Issysgen BIT NOT NULL DEFAULT 0,
Golivedate DATETIME NOT NULL DEFAULT GETDATE(),
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Staffs(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Usecode BIGINT NOT NULL UNIQUE,
Fullname VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
Username VARCHAR(100) NOT NULL UNIQUE,
Baseusername VARCHAR(100) NOT NULL UNIQUE,
Passwordhash VARCHAR(100) NOT NULL,
Pinhash VARCHAR(100) NOT NULL,
Phonenumber VARCHAR(15) NOT NULL UNIQUE,
Topuplimittype INT NOT NULL,
Topuplimitvalue DECIMAL(18,4) NOT NULL,
Rolecode BIGINT NOT NULL,
Acccode BIGINT NOT NULL,
Parentcode BIGINT NOT NULL DEFAULT 0,
Isactive BIT NOT NULL DEFAULT 1,
Isdeleted BIT NOT NULL DEFAULT 0,
Issysgen BIT NOT NULL DEFAULT 0,
Createdby BIGINT NOT NULL,
Modifiedby BIGINT NOT NULL,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE()
)


