CREATE TABLE Fumasitenants(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Tenantcode BIGINT NOT NULL UNIQUE DEFAULT 99,
Tenantname VARCHAR(100) NOT NULL UNIQUE DEFAULT 'Defautl Tenant',
Tenantkey VARCHAR(100) NOT NULL UNIQUE DEFAULT '0000-0000-0000-0000',
Tenantstatus INT NOT NULL DEFAULT 0,
Tenantconnid VARCHAR(50) NOT NULL,
Tenantconnkey VARCHAR(100) NOT NULL,
Tenantconndata VARCHAR(MAX) NOT NULL,
Tenantdatecreated DATETIME NOT NULL DEFAULT GETDATE(),
Tenantgolivedate DATETIME NOT NULL DEFAULT GETDATE()
)

/*  CONSTRAINT PK_Product PRIMARY KEY CLUSTERED (ProductID ASC),
  CONSTRAINT FK_Product_Tenant FOREIGN KEY (TenantId) REFERENCES dbo.Tenant(TenantId) */
CREATE TABLE Tenantstaffs(
 Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Staffcode BIGINT NOT NULL UNIQUE,
 Tenantcode BIGINT NOT NULL,
 Rolecode BIGINT NOT NULL DEFAULT 0,
 Firstname VARCHAR(50) NOT NULL,
 Lastname VARCHAR(50) NOT NULL,
 Emailaddress VARCHAR(100) NOT NULL UNIQUE,
 Phonenumber VARCHAR(15) NOT NULL UNIQUE,
 Staffpass VARCHAR(100) NOT NULL,
 Staffpin VARCHAR(100) NOT NULL,
 Staffstatus INT NOT NULL DEFAULT 3,
 Changepassword INT NOT NULL DEFAULT 1,
 Changepin INT NOT NULL DEFAULT 1,
 Topuplimittype VaRCHAR(100) NOT NULL,
 Topuplimitvalue DECIMAL(24,2) NOT NULL DEFAULT 0,
 Stationcode BIGINT NOT NULL,
 Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)


CREATE TABLE Staffroles(
 Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Rolecode BIGINT NOT NULL UNIQUE,
 Rolename VARCHAR(100) NOT NULL,
 Roledescription VARCHAR(100) NOT NULL,
 Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Permisions(
 Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Permisioncode BIGINT NOT NULL UNIQUE,
 Permisionname VARCHAR(100) NOT NULL,
  Permisiondesc VARCHAR(100) NOT NULL,
 Systemdate DATETIME NOT NULL DEFAULT GETDATE()
)


CREATE TABLE Permisionroles(
Permisioncode BIGINT NOT NULL,
Rolecode BIGINT NOT NULL
)


CREATE TABLE [dbo].[ItemCodes](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ItemCode] [varchar](5) NOT NULL,
	[Descr] [varchar](20) NOT NULL,
 CONSTRAINT [pk_ItemCodes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [uk_ItemCodes_ItemCode] UNIQUE NONCLUSTERED 
(
	[ItemCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RunningNos](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[RunningNo] [bigint] NOT NULL,
	[ItemCode] [varchar](5) NOT NULL,
 CONSTRAINT [pk_RunningNos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [uk_RunningNos_ItemCode] UNIQUE NONCLUSTERED 
(
	[ItemCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RunningNos]  WITH CHECK ADD  CONSTRAINT [fk_RunningNos_ItemCode] FOREIGN KEY([ItemCode])
REFERENCES [dbo].[ItemCodes] ([ItemCode])
GO

ALTER TABLE [dbo].[RunningNos] CHECK CONSTRAINT [fk_RunningNos_ItemCode]
GO

CREATE PROCEDURE [dbo].[Usp_GenerateRunNo]
	-- Add the parameters for the stored procedure here
	@ItemCode Varchar(5)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	Declare @CurrNo BIGINT

    -- Insert statements for procedure here
	Select top 1 @CurrNo = RunningNo From RunningNos Where ItemCode = @ItemCode
	If (@CurrNo IS NULL)
	Begin
		Set @CurrNo = 100
		Insert Into RunningNos(RunningNo,ItemCode) Values(@CurrNo,@ItemCode)
	End
	Else
	Begin
		Set @CurrNo = @CurrNo + 1
		Update RunningNos Set RunningNo = @CurrNo Where ItemCode = @ItemCode
	End

	SELECT @CurrNo As RunningNo
END
GO

CREATE TABLE Stations(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Stationcode BIGINT NOT NULL UNIQUE,
Tenantcode BIGINT NOT NULL,
Stationname VARCHAR(100) NOT NULL,
Stationaddress VARCHAR(100) NULL,
Stationlocation VARCHAR(200) NULL,
Stationreference VARCHAR(100) NULL,
Lng DECIMAL(18,2)  NULL DEFAULT 0,
Lat  DECIMAL(18,2) NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Stationshifts(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Shiftcode BIGINT NOT NULL UNIQUE,
Stationcode BIGINT NOT NULL,
Shiftname VARCHAR(10) NOT NULL,
Shiftstarttime TIME NOT NULL DEFAULT '00:00',
Shiftendtime TIME NOT NULL DEFAULT '11:59',
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Tenantcustomers(
 Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Customercode BIGINT NOT NULL UNIQUE,
  Tenantcode BIGINT NOT NULL,
 Firstname VARCHAR(100) NOT NULL,
 Lastname VARCHAR(100) NOT NULL,
 Phonenumber VARCHAR(15) NOT NULL,
 Emailaddress VARCHAR(100) NOT NULL,
 Customerpass VARCHAR(100) NOT NULL,
 Customerpin VARCHAR(100) NOT NULL,
 Station BIGINT NOT NULL,
 Canaccessprtal BIT NOT NULL DEFAULT 0,
 Customergrouping INT NOT NULL,--Individual 0,Corporate 1
 Customertype INT NOT NULL,--Prepaid 0,Postpaid 1
  Customerstatus INT NOT NULL DEFAULT 0,--0 active, 1 inactive 2 deleted
 Postpaidlimit DECIMAL(24,2) NOT NULL DEFAULT 0,
 Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)
CREATE TABLE Customerprepaidagreement(
 Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Agreementcode BIGINT NOT NULL UNIQUE,
 Customercode BIGINT NOT NULL,
 Agreementtype BIGINT NOT NULL,
 Agreementdesc VARCHAR(100) NOT NULL,
 Agreementdoc VARCHAR(100) NULL,
 Notes VARCHAR(100) NOT NULL,
 Isactive BIT NOT NULL DEFAULT 1,
Isdelete BIT NOT NULL DEFAULT 0,
 Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Customeragreementaccount(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Accountcode BIGINT NOT NULL UNIQUE,
Accountnumber BIGINT NOT NULL UNIQUE,
Agreementcode BIGINT NOT NULL,
Hasdrivercode BIT NOT NULL DEFAULT 0,
Isactive BIT NOT NULL DEFAULT 1,
Isdelete BIT NOT NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)
CREATE TABLE Identifiers(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Identifiercode BIGINT NOT NULL UNIQUE,
Identifiersno VARCHAR(100) NOT NULL,
Identifieruid VARCHAR(100) NOT NULL,
Typecode INT NOT NULL,
Isassigned BIT NOT NULL DEFAULT 0,
Isactive BIT NOT NULL DEFAULT 1,
Isdelete BIT NOT NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Identifiertype(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Typecode BIGINT NOT NULL UNIQUE,
Typename VARCHAR(100) NOT NULL,
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
)

CREATE TABLE Lnkaccountandidentifiers(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Accountcode BIGINT NOT NULL,
Identifiercode BIGINT NOT NULL UNIQUE,
Isparent BIT NOT NULL DEFAULT 1,
Isactive BIT NOT NULL DEFAULT 1,
Isdelete BIT NOT NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)

CREATE TABLE Agreementaccountemployee(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Employeecode BIGINT NOT NULL UNIQUE,
Accountcode BIGINT NOT NULL,
Firstname VARCHAR(100) NOT NULL,
Lastname VARCHAR(100) NOT NULL,
Phonenumber VARCHAR(15) NOT NULL,
Emailaddress VARCHAR(100) NOT NULL,
Drivercode VARCHAR(100) NOT NULL,
Isactive BIT NOT NULL DEFAULT 1,
Isdelete BIT NOT NULL DEFAULT 0,
Datecreated DATETIME NOT NULL DEFAULT GETDATE(),
Datemodified DATETIME NOT NULL DEFAULT GETDATE(),
Systemdate DATETIME NOT NULL DEFAULT GETDATE(),
Createdby VARCHAR(100) NOT NULL,
Modifiedby VARCHAR(100) NOT NULL
)